### ISSUE TITLE
Chatbot doesn't handle "bye" as an input

### ISSUE THREAD

**Issue by guru5590** [dice-group/sask#43]
Chatbot returns an exception, when handling "bye" as an input.

Attached is the screenshot of the exception:
<img width="1242" alt="screen shot 2018-04-30 at 10 48 03" src="https://user-images.githubusercontent.com/7804859/39420259-ffce6a6e-4c63-11e8-908f-1fa5bfade212.png">

Also, the log from the backend:
<img width="1362" alt="screen shot 2018-04-30 at 10 49 04" src="https://user-images.githubusercontent.com/7804859/39420293-26bfa89a-4c64-11e8-8036-9da4de8414cb.png">

P.S: Thanks Juzer for help identifying the issue.

**Comment by Juzerhk** [comment]
<img width="951" alt="chatbot_bye" src="https://user-images.githubusercontent.com/33219637/39672021-fccaad78-5122-11e8-99d6-bf4c3747095f.png">

ChatBot is now able to handle Bye Response

**Comment by guru5590** [comment]
@Juzerhk , Where is the code fixing this issue. I have not seen a pull request.

@Juzerhk , Please note , the issue can only be closed, when the code is reviewed and mergred into the master branch. And the issue ideally should be closed by the one who created the issue, not the one who was assigned the issue ( You in this case)

**Comment by Juzerhk** [comment]
This issue can easliy be fixed by making a small change in rivescript. So I made made changes in the rivescript rather then changing the code and that is what I have pushed it and now it is working fine.Regarding closing of the ticket, I will keep that in mind.On 6 May 2018 16:42, GuruPrasad <notifications@github.com> wrote:@Juzerhk , Where is the code fixing this issue. I have not seen a pull request.
@Juzerhk , Please note , the issue can only be closed, when the code is reviewed and mergred into the master branch. And the issue ideally should be closed by the one who created the issue, not the one who was assigned the issue ( You in this case)

**Comment by guru5590** [comment]
@Juzerhk If the code fix is in place. Please raise a pull request, so we can review the changes.

As mentioned, before once the fix is merged to the master branch. We will close this issue.

**Comment by guru5590** [comment]
@Juzerhk, the code changes you have made, just fixes the current issue. But it doesn't cover all scenarios as your masking a library issue with your code. I'll be closing this one, but in future a bug can be caused coz of this.
