### ISSUE TITLE
Chatbot incorrectly changes the filename extensions

### ISSUE THREAD

**Issue by Juzerhk** [dice-group/sask#49]
Filename extensions are incorrectly changed when typed from chatbot UI.
Below is the attached screenshot for reference.
<img width="954" alt="errorfilename" src="https://user-images.githubusercontent.com/33219637/40452455-2b4f1f54-5ee2-11e8-9c98-41269c0a5faa.png">

**Comment by prasanthhs** [comment]
@Juzerhk This is not a issue and it cannot be fixed from Language tool because File Name shouldn't be going to a spell checker tool as user can give any crazy file names. But there are some alternate options. I don't know if some of them work but it can be tried by you as a part of your requirement's permanent solution.

A. Prevent your entire message from going through Spell Check. Draw back : If user mistypes "Extract" as "Extrect" or  via as "vai" or something similar, then it won't be corrected. 

B. Let it go through Spell Check. But "escape" things which you don't want Spell check to handle. 
Adv: Corrects Basic spelling mistakes in extract etc while also protecting file Name etc from being Spell checked. 

C. Only pass necessary things to Spell check like Extract, Via , through etc to Spell Check and other things shouldn't.

Option B sounds good in theory. But i don't know if its possible to "Escape" File Names etc from Spell Check (Maybe putting File Name and other things which you don't want to be spell checked in quotes may escape it for example). But i don't know if it will work.

**Comment by Juzerhk** [comment]
Thanks. I will look into this. Need to find out an appropriate solution for this problem
