### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/sask#59]
Use to improve code over time https://codecov.io/

**Comment by guru5590** [comment]
Hi Ricardo,

I was experimenting with this, as I was made aware by the Intelligent data assistant team. 

For java its straight forward, we need to activate the sask repository in https://codecov.io/. 

Add a plugin to pom.xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>cobertura-maven-plugin</artifactId>
    <version>2.7</version>
    <configuration>
        <formats>
            <format>html</format>
            <format>xml</format>
        </formats>
        <check />
    </configuration>
</plugin>

and activate this in .travis.yml by adding

script:
  - mvn clean install -q -P linux cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash).

I was able to get it work in a seperate repository, Since I don't have admin access to sask repository if you activate it, I'll just add the other dependencies.

**Comment by guru5590** [comment]
@RicardoUsbeck , @prasanthhs 

Can you please enable the sask project in codecov.io. As I'm enabling travis to deploy the microservices on the latest work. I'll also enable the codecov plugin for the sask project.

Thanks,
Guru

**Comment by RicardoUsbeck** [comment]
Should be done.

**Comment by guru5590** [comment]
@RicardoUsbeck , Codecov has been integrated into the solution. Please find the screen shots indicating the same.
<img width="1680" alt="screen shot 2018-07-18 at 18 52 27" src="https://user-images.githubusercontent.com/7804859/42896025-eefe07d0-8abb-11e8-95c8-31b49d3bf7dc.png">
<img width="1680" alt="screen shot 2018-07-18 at 18 52 52" src="https://user-images.githubusercontent.com/7804859/42896030-efcf5e98-8abb-11e8-958e-dbce1581a05b.png">

Please let me know, if this is fine.

**Comment by RicardoUsbeck** [comment]
If it is documented in the wiki, you can close that issue

**Comment by guru5590** [comment]
Switch the Covertura maven plugin to JaCoCo. As Covertura plugin fails with java9.

``
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.7.9</version>
				<executions>
					<execution>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
``

**Comment by guru5590** [comment]
Closing the issue as the details are captured in the wiki page(https://github.com/dice-group/sask/wiki/Project-Quality-Certifications) as suggested by Ricardo.
