### ISSUE TITLE
Chatbot UI is not displaying responses from qa-service

### ISSUE THREAD

**Issue by sajjadpz** [dice-group/sask#79]
I am returning some response from Chatbot but UI doesn’t display anything. The `ResponseList` object contains information(answers) that is returned back to UI.

Probably something with the way UI is parsing the response object.
Any clue? since we need this to show something working on the UI.

@KHaack

**Comment by sajjadpz** [comment]
I am not in front of my laptop at the moment but what I can tell is that all the necessary fields are being populated that the webclient later uses to render them on UI. For instance entrylist inside ResponseList. 
Also you can check QaServiceHandler class in qa-ms branch for a quick look.

**Comment by prasanthhs** [comment]
We cannot guess what response is being passed. If you show what is exactly being passed to the ui from your code, we can find the cause more easily. Anyways, this is the general logic in UI. If there is a field displayText, it will display the displayText value as a hyperlink with the url attached to it. Can you check if entry.setDisplayText() is empty because it cannot be displayed as hyperlink.

**Comment by sajjadpz** [comment]
Please find below the attached screenshot of response returned by `chatbot` to `webclient`.

<img width="772" alt="screen shot 2018-07-13 at 6 16 41 pm" src="https://user-images.githubusercontent.com/9335671/42702158-f1ea7858-86c8-11e8-8a2d-ebc740c05e12.png">

**Comment by prasanthhs** [comment]
OK this would probably have to be checked. Since we don't have your set up, there are two options. One would be that if you can follow the chatbot ui code (under chatbot.js, function Name: addBigMessage ) then you can find what is going wrong here. Apart from this, one can also compare your response to response returned by the existing QA handler to identify what is different. Second option would be to provide detailed info on how we can debug the issue you are facing, from set up etc.  .

**Comment by sajjadpz** [comment]
I am already debugging that `addBigMessage` method but I will be slower since I don't have quite hands on with this UI code and all. In the mean while if someone has some time that can quickly reproduce the issue with following steps.

1.  Run `eureka`, `webclient` and `chatbot` in usual way.

2. within `qa-ms` component checkout `qs-ms` branch, yes branch name is the same as component name and run this component with usual spring-boot:run command like all other components.

3. from `Chatbot` UI type any query e.g "who is president of USA?" and you won't get any response back.

**Comment by prasanthhs** [comment]
@sajjadpz Sorry for the late reply. I checked your problem. You need to pass type of Messages contained in response List.  Currently it gets sets to default value as Plain text. But for plain text messages, url's etc won't be processed. It processes only "content" for plain text.

Set this responseList.setMessageType(MessageType.URL); OR responseList.setMessageType(MessageType.TEXT_WITH_URL); --> in case you want both Plain text behaviour and URL behaviour in your display.

**Comment by sajjadpz** [comment]
Thank you I have already resolved the issue, the issue was the same as you explained. Took a while to debug` javascript` though 😄  Thanks for help.
